export const allSkills = [
  "JavaScript",
  "TypeScript",
  "React",
  "Next.js",
  "Node.js",
  "Express.js",
  "Python",
  "Django",
  "Flask",
  "Java",
  "Spring Boot",
  "C#",
  ".NET",
  "Ruby",
  "Ruby on Rails",
  "PHP",
  "Laravel",
  "Go",
  "Rust",
  "Swift",
  "Kotlin",
  "HTML",
  "CSS",
  "Sass",
  "Tailwind CSS",
  "Bootstrap",
  "SQL",
  "PostgreSQL",
  "MySQL",
  "MongoDB",
  "Redis",
  "GraphQL",
  "REST APIs",
  "Docker",
  "Kubernetes",
  "AWS",
  "Google Cloud Platform (GCP)",
  "Microsoft Azure",
  "CI/CD",
  "Git",
  "GitHub",
  "GitLab",
  "Agile Methodologies",
  "Scrum",
  "Jira",
  "Figma",
  "Adobe XD",
  "Sketch",
  "UI Design",
  "UX Design",
  "UX Research",
  "Data Analysis",
  "Machine Learning",
  "Deep Learning",
  "TensorFlow",
  "PyTorch",
  "Scikit-learn",
  "Pandas",
  "NumPy",
  "Cybersecurity",
  "Penetration Testing",
  "Network Security",
  "DevOps",
  "Terraform",
  "Ansible",
  "Project Management",
  "Product Management",
  "Digital Marketing",
  "SEO",
  "SEM",
  "Content Marketing",
  "Sales",
  "Customer Support",
  "Communication",
  "Teamwork",
  "Problem Solving",
  "Leadership",
  "Time Management"
];
